AWSTemplateFromVersion: '2010-09-09'
Description: ec2 create

Resources: 
 # Define The Security Groupe
  WebServerSecurityGroupe:
   Type: AWS::EC2::SecurityGroupe
   Properties: 
    GroupeDescription: SSH access
    SecurityGroupeIngress: 
     -IpPortocol: tcp
     Formport: 22
     ToPort: 22
     CidrIp: 0.0.0.0/0
     
 # Define the ec2 instance
  MyEC2Instance:
   Type: AWS::EC2::Instance 
   Properties:
    InstanceType: t3.micro
    ImageId: ami-0fe18bc3cfa53a248
    Keyname: ohio jateen
    SecurityGroupeIds:
     -!Ref WebServerSecurityGroupe
     Tags:
      -key: Name
       Value: satyam